name: frontend_chatbot
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^10.1.0+1
  freezed_annotation: ^3.1.0
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  firebase_core: ^4.0.0
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  intl: ^0.20.2
  dartz: ^0.10.1
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  logger: ^2.6.1
  firebase_storage: ^13.0.0
  google_sign_in: ^6.2.0
  pull_to_refresh: ^2.0.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  path: ^1.9.1
  firebase_messaging: ^16.0.1
  awesome_notifications: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4
  freezed: ^3.1.0
  flutter_flavorizr: ^2.4.1
  flutter_gen_runner: ^5.10.0
  flutter_svg: ^2.2.0
  json_serializable: ^6.9.5
  mocktail: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_24pt-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

    - family: Waterfall
      fonts:
        - asset: assets/fonts/Waterfall-Regular.ttf
          weight: 400
